{{- if and (not (eq (toString .Values.ingress.enabled) `"false"`)) .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: {{ template "helm-guestbook.name" . }}-ingress
  namespace: default
spec:
  tls:
  - hosts:
    {{ toYaml .Values.ingress.hosts | indent 4 }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: guestbook.freshbrewed.science
    http:
      paths:
      - backend:
          service:
            name: {{ template "helm-guestbook.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: ImplementationSpecific
{{end}}